packages:
  - packages/*

overrides:
  'app-builder-lib>@electron/get': 4.0.3

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  electron-winstaller: false
  koffi: true
  node-pty: true
  protobufjs: false

minimumReleaseAgeExclude:
  - dshmarket@1.21.2
